### ISSUE TITLE
Add GitHub issue labels for data app and metadata app?

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-applications#105]
Would be nice to organize issues

Or merge the apps ;)

**Comment by alechenninger** [comment]
Note: I would do this if I could, but I don't have permissions to edit labels / assign labels to issues. Need someone higher up in the lightblue team :) ... @lightblue-platform/owners ?

**Comment by dcrissman** [comment]
It looks like the labels are basically correct, just with an extra. I will remove "duplicate". Is that what you were looking for?

**Comment by alechenninger** [comment]
I mean like, specifically a "data-app" label and a "metadata-app". The issues are hard to navigate because they generally refer to one or the other. I've resorted to prefixing issues with [data-mgmt] or something of the sort but it seems like a label would be better.

**Comment by dcrissman** [comment]
I don't see any problem with that. Done.

**Comment by alechenninger** [comment]
Awesome! Now if only I could assign labels to issues :)
