### ISSUE TITLE
Fix roles (lightblue-metadata-admin vs lb-metadata-admin)

### ISSUE THREAD

**Issue by paterczm** [lightblue-platform/lightblue-applications#111]
web.xml is referencing lightblue-metadata-admin, ui is referencing lb-metadata-admin. Looks like you need to be in both to use metadata mgmt app. This needs to be consolidated.

**Comment by jewzaam** [comment]
Consolidate on lb-metadata-admin to be consistent with other roles we've been using (prefix of 'lb-')?

**Comment by BVulaj** [comment]
I'll take this one.
