### ISSUE TITLE
Sort entity names and versions in dropdowns (metadata mgmt app)

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-applications#72]
They're not sorted.  The entity list we have is getting big, so it's harder to find what I want.  Also versions, at least in dev, are getting long in some cases and not being sorted is annoying.

**Comment by alechenninger** [comment]
You're referring to the data management app here I assume?

**Comment by jewzaam** [comment]
metadata mgmt app

**Comment by jewzaam** [comment]
@paterczm this in progress?
