### ISSUE TITLE
Data mgmt app: Javascript displayed instead of environment dropdown

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-applications#91]
![image](https://cloud.githubusercontent.com/assets/480388/7008450/b8274e72-dc60-11e4-9606-00708026c67f.png)
Notice the dropdown that should be environments is showing some javascript.
I do not know how to reproduce it.  It took some work to get it to go away.  I *think* I ended up clicking on the arrow that should have listed configured environments (to the right of the javascript in the UI) and was redirected to the manage environments page with the UI having fixed itself.

**Comment by alechenninger** [comment]
So this shows up before Angular bootstraps your html. If it showed up permanently for you, then it means something went wrong when Angular was initializing.

I can get this to not show up during initialization, however, by using the [ngCloak](https://docs.angularjs.org/api/ng/directive/ngCloak) directive.

**Comment by alechenninger** [comment]
I think what caused this was unrelated, though using `ngCloak` is implemented in the dependency refactoring in #89

**Comment by alechenninger** [comment]
@jewzaam I think this can be closed. IIRC the issue you saw was because of a deployment issue, and the momentary angular expression that shows up before the app is fully loaded has been resolved with the `ngCloak` directive added in #89 .
