### ISSUE TITLE
Metadata mgmt app: remove disabled versions from drop down

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-applications#92]
The app doesn't allow you to manage status of schema.  So let's remove the disabled versions from the interface.  They're just cluttering up things.

**Comment by jewzaam** [comment]
Blocked until https://github.com/lightblue-platform/lightblue-applications/issues/81 is done

**Comment by paterczm** [comment]
I would prefer to complete https://github.com/lightblue-platform/lightblue-applications/issues/81 first.

**Comment by jewzaam** [comment]
How much time to do #81 vs this issue as it is today?  The UI for the app is getting messy with the disabled versions that shouldn't be visible.  If it's a quick thing to change, then I say go ahead and change it.

**Comment by paterczm** [comment]
It's a one-liner.
